matrix:
   include:
    #######################
    #    Docker Matrix     #
    #######################
     - language: generic
       dist: xenial
       script:
         - docker build -t $DOCKER_USER/cakechat-openshift:latest
       if: branch = release
       after_success:
         - docker login -u $DOCKER USER -p $DOCKER_PASS
         - docker push $DOCKER_USER/cakechat-openshift:latest
    #######################
    #   OpenShift Matrix  #
    #######################
     - language: generic
       dist: xenial
       install:
        - wget -qO - https://github.com/openshift/origin/releases/download/v3.11.0/openshift-origin-client-tools-v3.11.0-0cbc58b-linux-64bit.tar.gz | tar -xzvf -
        - chmod -R 755 openshift-origin-client-tools-v3.11.0-0cbc58b-linux-64bit/oc
        - sudo cp -vRf openshift-origin-client-tools-v3.11.0-0cbc58b-linux-64bit/oc /usr/bin
        - rm -rf openshift-origin-client-tools-v3.11.0-0cbc58b-linux-64bit
       script:
         - docker build -t registry.starter-us-east-2.openshift.com/$OPENSHIFT_NAMESPACE/cakechat:latest .
       if: branch = staging
       after_success:
         - oc login https://api.starter-us-east-2.openshift.com -u $OPENSHIFT_USER -p $OPENSHIFT_PASSWORD
         - docker login registry.starter-us-east-2.openshift.com -u $(oc whoami) -p $(oc whoami -t)
         - docker push registry.starter-us-east-2.openshift.com/$OPENSHIFT_NAMESPACE/cakechat:latest
         - oc project $OPENSHIFT_NAMESPACE
         - oc new-app registry.starter-us-east-2.openshift.com/$OPENSHIFT_NAMESPACE/cakechat:latest
         - oc expose dc/frontend --port=8080

notifications:
     email: false